"""Constants"""

VERSION = "0.1.0"

# Default arguments
MAX_IN_QUEUE = 5000
MAX_OUT_QUEUE = 5000
MAX_CONCURRENCY = 1000
WORKER_COUNT = 200
BANNER_TYPES = ["ssh"]
CONNECTION_TIMEOUT = 1.0
READ_TIMEOUT = 1.0

SENTINEL = object()
